/*
 * Global_Config.c
 *
 *  Created on: Dec 24, 2016
 *      Author: 
 */

#include "Cpu.h"
#include "Status.h"
#include "Digital_IO.h"
#include "keyhandler.h"
#include "ADC_Handler.h"
#include "Global_Config.h"


/*Digital IO configuration */
/*	port_config; * port_dir; * port_data; pin; direction; config; default_level; */
const Digital_IO_Config_st Digital_IO_Pins[DIGITAL_IO_COUNT] = 
{
		{ &PORTC_PCR9, &GPIO_PDDR_REG(PTC_BASE_PTR), &GPIO_PDIR_REG(PTC_BASE_PTR), 9, DIGITAL_IO_DIR_INPUT, DIGITAL_IO_INPUT_TRISTATE, DIGITAL_IO_LEVEL_INVALID},
		{ &PORTC_PCR10, &GPIO_PDDR_REG(PTC_BASE_PTR), &GPIO_PDIR_REG(PTC_BASE_PTR), 10, DIGITAL_IO_DIR_INPUT, DIGITAL_IO_INPUT_TRISTATE, DIGITAL_IO_LEVEL_INVALID},
		{ &PORTC_PCR11, &GPIO_PDDR_REG(PTC_BASE_PTR), &GPIO_PDIR_REG(PTC_BASE_PTR), 11, DIGITAL_IO_DIR_INPUT, DIGITAL_IO_INPUT_TRISTATE, DIGITAL_IO_LEVEL_INVALID},
		
		{ &PORTB_PCR0, &GPIO_PDDR_REG(PTB_BASE_PTR), &GPIO_PDOR_REG(PTB_BASE_PTR), 0, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
		{ &PORTB_PCR1, &GPIO_PDDR_REG(PTB_BASE_PTR), &GPIO_PDOR_REG(PTB_BASE_PTR), 1, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
		{ &PORTB_PCR2, &GPIO_PDDR_REG(PTB_BASE_PTR), &GPIO_PDOR_REG(PTB_BASE_PTR), 2, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
		{ &PORTB_PCR3, &GPIO_PDDR_REG(PTB_BASE_PTR), &GPIO_PDOR_REG(PTB_BASE_PTR), 3, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
		{ &PORTB_PCR16, &GPIO_PDDR_REG(PTB_BASE_PTR), &GPIO_PDOR_REG(PTB_BASE_PTR), 16, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
		{ &PORTB_PCR17, &GPIO_PDDR_REG(PTB_BASE_PTR), &GPIO_PDOR_REG(PTB_BASE_PTR), 17, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
		{ &PORTB_PCR18, &GPIO_PDDR_REG(PTB_BASE_PTR), &GPIO_PDOR_REG(PTB_BASE_PTR), 18, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
		{ &PORTB_PCR19, &GPIO_PDDR_REG(PTB_BASE_PTR), &GPIO_PDOR_REG(PTB_BASE_PTR), 19, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
};

const Digital_IO_Config_st Display_IO[6] = 
{
		/*Display pins*/
		{ &PORTD_PCR0, &GPIO_PDDR_REG(PTD_BASE_PTR), &GPIO_PDOR_REG(PTD_BASE_PTR), 0, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
		{ &PORTD_PCR1, &GPIO_PDDR_REG(PTD_BASE_PTR), &GPIO_PDOR_REG(PTD_BASE_PTR), 1, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
		{ &PORTD_PCR2, &GPIO_PDDR_REG(PTD_BASE_PTR), &GPIO_PDOR_REG(PTD_BASE_PTR), 2, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
		{ &PORTD_PCR3, &GPIO_PDDR_REG(PTD_BASE_PTR), &GPIO_PDOR_REG(PTD_BASE_PTR), 3, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
		{ &PORTD_PCR4, &GPIO_PDDR_REG(PTD_BASE_PTR), &GPIO_PDOR_REG(PTD_BASE_PTR), 4, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
		{ &PORTD_PCR5, &GPIO_PDDR_REG(PTD_BASE_PTR), &GPIO_PDOR_REG(PTD_BASE_PTR), 5, DIGITAL_IO_DIR_OUTPUT, DIGITAL_IO_OUTPUT_PUSHPULL, DIGITAL_IO_LEVEL_LOW},
};

/*Keyhandler configuration */
/* List of pins and their configuration details for all keys */
const keyhandler_conf_st key_list[KEYS_COUNT] = 
{
		{(GPIO_MemMapPtr)PTC_BASE_PTR, 8U, &PORTC_PCR8, (uint32_t)(PORT_PCR_INPUT | PORT_PCR_INT_PULL)},/*Key 1 - Start/stop*/
		{(GPIO_MemMapPtr)PTC_BASE_PTR, 7U, &PORTC_PCR7, (uint32_t)(PORT_PCR_INPUT | PORT_PCR_INT_PULL)},/*Key 2 - Mode*/
		{(GPIO_MemMapPtr)PTC_BASE_PTR, 6U, &PORTC_PCR6, (uint32_t)(PORT_PCR_INPUT | PORT_PCR_INT_PULL)},/*Key 3 - Water*/
		{(GPIO_MemMapPtr)PTC_BASE_PTR, 5U, &PORTC_PCR5, (uint32_t)(PORT_PCR_INPUT | PORT_PCR_INT_PULL)},/*Key 4 - Menu*/
};


/*ADC configuration*/
const ADC_Config_st ADC_Config[] = 
{
		/*P-SEN*/
		{ADC0_BASE_PTR, 0, ADC_SINGLE_ENDED,
				/*ADC0_DP0*/
				.pin_config = {(GPIO_MemMapPtr)NULL, 0U, NULL, 0U}},
		/*CMB-T*/
		{ADC0_BASE_PTR, 3, ADC_SINGLE_ENDED,
				/*ADC0_DP3*/
				.pin_config = {(GPIO_MemMapPtr)NULL, 0U, NULL, 0U}},
		/*Boiler-T*/
		{ADC0_BASE_PTR, 6/*ADC0_SE6*/, ADC_SINGLE_ENDED,
				/*PTE18*/
				.pin_config = {(GPIO_MemMapPtr)PTE_BASE_PTR, 18U, &PORTE_PCR18, (uint32_t)(PORT_PCR_ANALOG)}},
		/*BAND-T*/
		{ADC0_BASE_PTR, 7, ADC_SINGLE_ENDED,
				/*PTE19*/
				.pin_config = {(GPIO_MemMapPtr)PTE_BASE_PTR, 19U, &PORTE_PCR19, (uint32_t)(PORT_PCR_ANALOG)}},

};
